machinefi/w3bstream

Makefile
docker-compose.yaml

1. rename local build docker image to `$(USER)/w3bstream:main`
2. default docker image to `ghcr.io/machinefi/w3bstream:main`

docker image rename

---

docker-compose.yaml

map 1883 from mqtt server docker container

export port of mqtt server

---

Makefile
docker-compose.yaml

introduce `DOCKER_COMPOSE_FILE`
reuse `run_docker`
hardcode default image versions

update make file and default image

---

cmd/srv-applet-mgr/apis/middleware/current_user.go
pkg/models/project.go
pkg/modules/project/project.go
pkg/modules/strategy/strategy.go

feat: mute Project.Name when update project use models.ProjectBase

---

.gitignore
build/var/mqtt/conf/mosquitto.conf
cmd/srv-applet-mgr/apis/middleware/current_user.go
go.mod
pkg/errors/status/error.go
pkg/errors/status/error__generated.go
pkg/types/context.go
testutil/docker-compose-pg.yaml

issue #210
* add `Project`, `Applet` and `Instance` context to current user
* add status error `InvalidAuthValue` `InvalidAuthAccountID` and `NoProjectPermission`
* add `CtxInstance`
* revert build/var/mqtt/conf/mosquitto.conf
* update testutil/docker-compose-pg.yaml

feat: current user contexts

---

go.mod
go.sum
pkg/modules/vm/wasmtime/instance.go
pkg/modules/vm/wasmtime/instance_exports.go

support sql db

---

Makefile
docker-compose.yaml

fix docker envs

---

pkg/modules/vm/instance_new.go
pkg/modules/vm/kvdb/mem_db.go
pkg/modules/vm/kvdb/redis_db.go
pkg/modules/vm/wasmtime/instance.go
pkg/modules/vm/wasmtime/instance_exports.go
pkg/types/wasm/enums.go
pkg/types/wasm/instance.go

#269
merge mem_db & redis_db into a interface

Add a interface with key value db

---

cmd/srv-applet-mgr/apis/applet/del.go
pkg/modules/applet/applet.go
pkg/modules/project/project.go
pkg/wsctl/client/client.go
pkg/wsctl/cmd/applet/applet.go
pkg/wsctl/cmd/applet/create.go
pkg/wsctl/cmd/applet/delete.go
pkg/wsctl/cmd/instance/delete.go
pkg/wsctl/cmd/instance/start.go
pkg/wsctl/cmd/instance/stop.go
pkg/wsctl/cmd/project/create.go
pkg/wsctl/cmd/project/delete.go
pkg/wsctl/cmd/project/project.go
pkg/wsctl/cmd/publisher/create.go
pkg/wsctl/cmd/publisher/delete.go
pkg/wsctl/cmd/publisher/publisher.go
pkg/wsctl/cmd/types/types.go
pkg/wsctl/cmd/utils/utils.go

Add cmds into wsctl

---

Makefile
pkg/depends/conf/mqtt/mqtt_client.go
pkg/modules/mq/mqtt.go

Fix subscribe issue in mqtt

---

HOWTO.md
pkg/types/context.go

add `WithRedis` func in `./pkg/types/context.go`

[chore]add WithRedis

---

pkg/errors/status/error__generated.go
pkg/models/account.go
pkg/modules/deploy/instance_context.go
pkg/types/wasm/wasm_config_chain_client.go

Fix acquiring the account from middleware

---

cmd/srv-applet-mgr/global/config.go
pkg/errors/status/error.go
pkg/errors/status/error__generated.go
pkg/models/account.go
pkg/modules/account/account_eth.go
pkg/types/context.go
pkg/types/types.go

feat: eth address account white list

---

pkg/depends/base/consts/comms.go
pkg/models/wasm_log.go
pkg/modules/job/log_task.go

change wasm_log msg length

---

pkg/modules/event/event.go

[bug]checkout event header

---

pkg/depends/conf/http/mws/prometheus.go
pkg/depends/conf/jwt/jwt.go
pkg/models/project.go
pkg/modules/event/event.go
pkg/modules/project/project.go
pkg/modules/publisher/publisher.go
pkg/modules/vm/wasmtime/instance.go
pkg/modules/vm/wasmtime/instance_exports.go
pkg/modules/vm/wasmtime/task.go
pkg/types/wasm/context.go
pkg/types/wasm/instance.go

wasm context event type

---

cmd/srv-applet-mgr/apis/root.go
cmd/srv-applet-mgr/config/config.yml.template
cmd/srv-applet-mgr/global/config.go
cmd/srv-applet-mgr/main.go
pkg/depends/kit/validator/validator_z_strfmt_test.go

expose event recv port

---

cmd/srv-applet-mgr/apis/project/del.go
cmd/srv-applet-mgr/apis/project/get.go
pkg/depends/kit/httptransport/transformer/util_param.go
pkg/depends/kit/validator/strfmt/internal/main/main.go
pkg/depends/util/strfmt/strfmt.go
pkg/depends/util/strfmt/strfmt_generated.go
pkg/depends/util/strfmt/zz_test.go
pkg/models/project.go
pkg/modules/project/project.go

project name validate

---

.pre-commit-config.yaml

Qevan, could u pls help to reveiw the config for the precommition hook, thx.

add the config for the function of detecting of private key

---

pkg/modules/deploy/instance_context.go
pkg/modules/vm/wasmtime/instance_exports.go
pkg/types/wasm/instance.go
pkg/types/wasm/wasm_config_mqtt.go

add wasm send mqtt feature

---

Dockerfile
Makefile
cmd/entrypoint.sh

change the RUN command.

---

pkg/depends/conf/app/app_ctx.go
pkg/depends/conf/tls/tls.go

fix panic caused by unconfigurated tls. and output init error module

fix(conf.tls): fix unconfigurated tls

---

pkg/models/publisher.go
pkg/models/publisher__generated.go
pkg/modules/publisher/publisher.go

Allow the same publisher key to be created by different account

Remove the uniqueness of publisher key

---

cmd/srv-applet-mgr/apis/cronjob/get.go
cmd/srv-applet-mgr/openapi.json
go.mod
go.sum

remove cron job list tag

---

cmd/srv-applet-mgr/openapi.go
cmd/srv-applet-mgr/openapi.json
pkg/depends/util/strfmt/strfmt.go
pkg/depends/util/strfmt/zz_test.go
pkg/models/applet.go
pkg/modules/config/config.go
pkg/modules/project/project.go
pkg/modules/strategy/strategy.go
pkg/types/wasm/wasm_config_database_test.go

clickup issue: https://app.clickup.com/t/866a5p0p5

fix(project): create project failed

---

cmd/srv-applet-mgr/openapi.json
pkg/models/account.go
pkg/models/account__generated.go

account-uniq-index

---

cmd/srv-applet-mgr/openapi.json
pkg/errors/status/error.go
pkg/errors/status/error__generated.go
pkg/modules/account/account.go
pkg/modules/account/account_eth.go

remove account old code

---

cmd/srv-vm-instances/apis/event/get.go

Remove deprecated code. No file imports this pkg

Remove unused code

---

HOWTO.md
docker-compose.yaml
pkg/types/wasm/wasm_config_database.go

chore(doc): update HOWTO and docker-compose

---

.github/workflows/ci.yml

Following the steps here: https://app.codecov.io/gh/machinefi/w3bstream/new

Update ci.yml to enable codecov

---

.github/workflows/build_and_post_docker_image.yml
.github/workflows/ci.yml
.github/workflows/release.yml

add the output of the commit id for ci, docker image builder and release workflow.

add the output of commit id.

---

pkg/modules/resource/resource.go

fix(resource): update resource meta when user upload file

---

pkg/modules/applet/applet_models.go

chore(project): response instance id in project.ListDetail

---

cmd/srv-applet-mgr/apis/monitor/del.go

​https://app.clickup.com/t/866a7wa55

fix(monitor): del monitor

---

HOWTO.md

fix monitor howto

---

docker-compose.local.yaml
docker-compose.yaml

clickup: https://app.clickup.com/t/864ekbbf1

fix(docker-compose): env vars

---

pkg/models/account__generated.go
pkg/models/contract_log.go
pkg/models/contract_log__generated.go
pkg/modules/blockchain/monitor.go

https://app.clickup.com/t/864em6hkf
https://app.clickup.com/t/864em6jqp

fix(monitor): change ContractLog uniq, add event result judge

---

cmd/srv-applet-mgr/main.go
pkg/modules/operator/migrate.go

https://app.clickup.com/t/866a955e7

fix(operator): support account private migrate

---

CONTRIBUTING.md

Contributing.md is a guideline for community to contribute code to the project.

[DOC] Create CONTRIBUTING.md

---

pkg/modules/blockchain/monitor.go

https://app.clickup.com/t/864emg78h

perf(monitor): scan blockchain faster

---

pkg/modules/applet/applet_models.go
pkg/modules/resource/resource_util.go

Clean up unused code
https://app.clickup.com/t/866a8j7eh

chore(code): clear code

---

cmd/srv-applet-mgr/apis/event/pos.go
cmd/srv-applet-mgr/config/config.yml.template
cmd/srv-applet-mgr/global/config.go
cmd/srv-applet-mgr/openapi.json
cmd/srv-applet-mgr/tasks/task_db_log.go
go.mod
go.sum
pkg/modules/event/event.go
pkg/modules/job/log_task.go
pkg/modules/vm/wasmtime/instance.go
pkg/modules/vm/wasmtime/instance_exports.go
pkg/modules/vm/wasmtime/task.go
pkg/types/context.go

chore(log): add log to critical processes #609

---

.github/workflows/ci.yml
cmd/srv-applet-mgr/tests/requires/endpoints.go
go.mod
go.sum
pkg/depends/kit/httptransport/client/client_test.go

1. ci: do test before build image
2. code: ignore client.TestClient on macOS, reason:https://github.com/actions/runner-images/issues/4896

chore(ci): run test before build image

---

cmd/srv-applet-mgr/apis/publisher/pos.go
pkg/modules/publisher/publisher.go

chore(publisher): adjusting the parameters for the create publisher

---

cmd/srv-applet-mgr/tests/integrations/contract_log_test.go
go.mod
go.sum

test(monitor): add contract log integration test

---

pkg/depends/kit/mq/task_worker.go

[BUGFIX](LOG) add more logs in task worker

---

Makefile
cmd/srv-applet-mgr/openapi.go

Remove legacy dependency of patch-0.0.3

rm old dependency

---

cmd/srv-applet-mgr/tests/integrations/applet_test.go

test(applet): add applet integration test

---

Makefile
cmd/srv-applet-mgr/Makefile
cmd/srv-applet-mgr/tests/integrations/publisher_test.go
cmd/srv-applet-mgr/tests/integrations/resource_test.go
cmd/srv-applet-mgr/tests/integrations/strategy_test.go
go.mod
pkg/types/types.go

1. move create project and applet from subtest
2. update precommit cmd
3. fix gen openapi

chore(test): move create project and applet from subtest

---

cmd/srv-applet-mgr/openapi.json
pkg/modules/account_identity/zz_account_identity_test.go
pkg/modules/blockchain/contract_test.go

feat(chore): account_identity module unit test

---

cmd/srv-applet-mgr/apis/monitor/put.go
cmd/srv-applet-mgr/apis/monitor/root.go
cmd/srv-applet-mgr/openapi.json
pkg/enums/monitor_cmd.go
pkg/enums/monitor_cmd__generated.go
pkg/errors/status/error.go
pkg/errors/status/error__generated.go
pkg/models/chain_height.go
pkg/models/chain_height__generated.go
pkg/models/chain_tx.go
pkg/models/chain_tx__generated.go
pkg/models/contract_log.go
pkg/models/contract_log__generated.go
pkg/modules/blockchain/api.go
pkg/modules/blockchain/api_contract.go
pkg/modules/blockchain/api_height.go
pkg/modules/blockchain/api_tx.go
pkg/modules/blockchain/contract.go
pkg/modules/blockchain/height.go
pkg/modules/blockchain/tx.go
pkg/modules/project/project.go

https://app.clickup.com/t/864eewj2q

feat(blockchain): support monitor pause/start

---

cmd/srv-applet-mgr/openapi.json
go.mod
go.sum
pkg/modules/strategy/strategy_test.go

chore(strategy): add unit test

---

cmd/srv-applet-mgr/openapi.json
pkg/modules/resource/resourece_test.go

chore(resource): add unit test

---

pkg/modules/applet/applet.go
pkg/modules/applet/zz_applet_test.go
pkg/test/mock_depends_kit_sqlx/error.go

chore(test): applet module test

---

cmd/srv-applet-mgr/apis/event/pos.go
cmd/srv-applet-mgr/apis/event/root.go
cmd/srv-applet-mgr/apis/root.go

add a router `/event2` to handle the device&data pushed directly from server

Support device&data pushed from cloud

---

pkg/modules/metrics/auto_collect.go

1. fix get longitude from json
2. if there is no geo infos, then do not insert db

hotfix(geo): get longitude from json

---

cmd/srv-applet-mgr/config/config.yml.template
cmd/srv-applet-mgr/global/config.go
cmd/srv-applet-mgr/tests/requires/endpoints.go
go.mod
pkg/modules/vm/risc0vm/risc0.go
pkg/modules/vm/risc0vm/risc0_models.go
pkg/modules/vm/wasmapi/handler/gen_proof.go
pkg/modules/vm/wasmapi/handler/handler.go
pkg/modules/vm/wasmapi/server.go
pkg/types/types.go

* add risc endpoint in config
* integrate with risc0 server
* add wasmapi for zkp

feat(abi): add abi for generate zk proof in wasm
